name: Publish Docker Image

on:
  push:
    branches: [ "main", "iteration1", "iteration2", "iteration3"]
  pull_request:
    branches: [ "main", "iteration1", "iteration2", "iteration3"]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD}}
       
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with: 
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:frontend
            build-args: |
              FLASK_ENV=production
            no-cache: true